workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - build
  - test
  - deploy

build-code-job:
  stage: build
  script:
    - echo "Check the ruby version, then build some Ruby project files:"

test-code-job1:
  stage: test
  script:
    - echo "If the files are built successfully, test some files with one command:"


test-code-job2:
  stage: deploy
  image: alpine/helm:3.9.1
  script:
    - ls -la
    - helm repo add jhidalgo3-github https://jhidalgo3.github.io/helm-charts/
    - helm upgrade --install my-hello-kubernetes-chart jhidalgo3-github/hello-kubernetes-chart --version 3.0.0 -n hello-test

test-code-job3:
  stage: deploy
  image: alpine/helm:3.9.1
  script:
    - cd helmcharts
    - helm upgrade --install mydemochart mydemo -n test2