stages:
  - sonar-scan
  - build
  - deploy
  - test
  - deploy-prod

sonar-scan-merge:
  stage: sonar-scan  
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' 
  script:
    - sonar-scanner
  allow_failure: true

build-wagtail-check:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' 
  script:
    - >-
      /kaniko/executor
      --context "application/mysite"
      --dockerfile "application/mysite/Dockerfile"
      --no-push 
      
sonar-scan-dev:
  stage: sonar-scan
  tags:
#    - docker
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH         
  script:
    - sonar-scanner
  allow_failure: true

build-wagtail-dev:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      variables:
        IMAGE_TAG: "$CI_COMMIT_SHORT_SHA-dev"      
  script:
    - declare -i v+=1 
    - >-
      /kaniko/executor
      --context "application/mysite"
      --dockerfile "application/mysite/Dockerfile"
      --destination "gcr.io/internship87task8/wagtail:$v"

deploy-dev:
  stage: deploy
  image: alpine/helm:3.9.1
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      variables:
        IMAGE_TAG: "$CI_COMMIT_SHORT_SHA-dev" 
  script:
    - cd helmcharts
    - helm upgrade --install app-dev app-dev-helmChart -n dev    

health-wagtail-dev:
  stage: test
  image: wbitt/network-multitool
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH      
  script:
    - nslookup dev.prtest.tech
    - curl https://dev.prtest.tech
      
sonar-scan-stage:
  stage: sonar-scan
  tags:
#    - docker
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  rules:    
    - if: $CI_COMMIT_TAG
      variables:
        IMAGE_TAG: $CI_COMMIT_TAG        
  script:
    - sonar-scanner
  allow_failure: true
  

build-wagtail-stage:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  rules:
    # - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    #   variables:
    #    IMAGE_TAG: "$CI_COMMIT_SHORT_SHA-dev"
    - if: $CI_COMMIT_TAG
      variables:
        IMAGE_TAG: $CI_COMMIT_TAG   
  script:
    - >-
      /kaniko/executor
      --context "application/mysite"
      --dockerfile "application/mysite/Dockerfile"
      --destination "gcr.io/internship87task8/wagtail:latest"
    

deploy-stage:
  stage: deploy
  image: alpine/helm:3.9.1
  rules:
    # - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    #   variables:
    #     IMAGE_TAG: "$CI_COMMIT_SHORT_SHA-dev"
    - if: $CI_COMMIT_TAG
      variables:
        IMAGE_TAG: $CI_COMMIT_TAG 
  script:
    - cd helmcharts
    - helm upgrade --install app-stage app-stage-helmChart -n stage    
  


health-wagtail-stage:
  stage: test
  image: wbitt/network-multitool
  rules:
    # - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    #   variables:
    #     IMAGE_TAG: "$CI_COMMIT_SHORT_SHA-dev"
    - if: $CI_COMMIT_TAG
      variables:
        IMAGE_TAG: $CI_COMMIT_TAG 
  script:
    - nslookup stage.prtest.tech
    

deploy-production:
  stage: deploy-prod  
  image: alpine/helm:3.9.1
  rules:
    # - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    #   variables:
    #     IMAGE_TAG: "$CI_COMMIT_SHORT_SHA-dev"
    - if: $CI_COMMIT_TAG
      variables:
        IMAGE_TAG: $CI_COMMIT_TAG 
  script:
    - cd helmcharts
    - helm upgrade --install app-production app-prod-helmChart -n production
       
  when: manual




