workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - sonar-scan-dev
  - build-dev
  - deploy-dev
  - test-dev
  - sonar-scan-stage
  - build-stage
  - deploy-stage
  - test-stage
  - deploy-production

sonar-scan-dev:
  stage: sonar-scan-dev
  tags:
#    - docker
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  allow_failure: true

build-wagtail-dev:
  stage: build-dev
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - >-
      /kaniko/executor
      --context "application/mysite"
      --dockerfile "application/mysite/Dockerfile"
      --destination "gcr.io/internship87task8/wagtail:latest"

deploy-dev:
  stage: deploy-dev
  image: alpine/helm:3.9.1
  script:
    - cd helmcharts
    - helm upgrade --install app-dev app_helmChart -n dev    

health-wagtail-dev:
  stage: test-dev
  image: wbitt/network-multitool
  script:
    - nslookup dev.prtest.tech
      
sonar-scan-stage:
  stage: sonar-scan-stage
  tags:
#    - docker
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  allow_failure: true
  when: manual

build-wagtail-stage:
  stage: build-stage
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - >-
      /kaniko/executor
      --context "application/mysite"
      --dockerfile "application/mysite/Dockerfile"
      --destination "gcr.io/internship87task8/wagtail:latest"
  needs: [sonar-scan-stage]   

deploy-stage:
  stage: deploy-stage
  image: alpine/helm:3.9.1
  script:
    - cd helmcharts
    - helm upgrade --install app-stage app_helmChart -n stage    
  needs: [build-wagtail-stage]


health-wagtail-stage:
  stage: test-stage
  image: wbitt/network-multitool
  script:
    - nslookup stage.prtest.tech
  needs: [deploy-stage]  

deploy-production:
  stage: deploy-production
  image: alpine/helm:3.9.1
  script:
    - cd helmcharts
    - helm upgrade --install app-production app_helmChart -n production    
  when: manual




