
apiVersion : apps/v1
kind: Deployment
metadata:
  name: web-deployment-autoscaling
  labels:
    app : k8s-deployment
spec:
  selector:
    matchLabels:
      project: internship87task8
  template:
    metadata:
      labels:
        project: internship87task8   # Service will look for those PODS Labels!!!
    spec:
      containers:
        - name : app-wagtail
          image: ghcr.io/wagtail:latest
          ports:
            - containerPort: 8000


---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta2
    kind: Deployment
    name: web-deployment-autoscaling
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 80

