
apiVersion : {{ .Values.app.apiVersion} }
kind: Deployment
metadata:
  name: {{ .Values.app.metadata.name }}
  labels:
    app : {{ .Values.app.metadata.labels.app }}
spec:
  selector:
    matchLabels:
      project: {{ .Values.app.project }}
  template:
    metadata:
      labels:
        project: {{ .Values.app.project }}   # Service will look for those PODS Labels!!!
    spec:
      containers:
        - name : {{ .Values.app.apiVersion}}
          image: {{ .Values.app.apiVersion}}
          ports:
            - containerPort: {{ .Values.app.apiVersion}}


---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta2
    kind: Deployment
    name: web-deployment-autoscaling
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 80

