apiVersion: {{ .Values.ingress.apiVersion }}
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.app.host }}
    - {{ .Values.ingress.sonarqube.host }}   
    
    secretName: {{ .Values.ingress.secretName }}
  rules:

  - host: {{ .Values.ingress.app.host }}
    http:
        paths:
          - pathType: {{ .Values.ingress.app.pathType }}
            path: {{ .Values.ingress.app.path }}
            backend:
              service:
                name: {{ .Values.ingress.app.name }}
                port: 
                  number: {{ .Values.ingress.app.port.number }}  

  - host: {{ .Values.ingress.sonarqube.host }}
    http:
        paths:
          - pathType: {{ .Values.ingress.sonarqube.pathType }}
            path: {{ .Values.ingress.sonarqube.path }}
            backend:
              service:
                name: {{ .Values.ingress.sonarqube.name }}
                port: 
                  number: {{ .Values.ingress.sonarqube.port.number }}   
   