apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - wagtail.prtest.tech
    - sonar.prtest.tech   
    
    secretName: app-tls
  rules:

  - host: sonar.prtest.tech
     http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: sonarqube
                port: 
                  number: 9000   

   - host: wagtail.prtest.tech
     http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: autoscaling-pod-service
                port: 
                  number: 8000
   