
apiVersion: v1
kind: Service
metadata:
  name: autoscaling-pod-service
  labels:
     env  : prod
spec:
  selector:
    project: {{ .Values.app.project }}    # Selecting PODs with those Labels
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 80  # Port on Load Balancer
      targetPort: 8000  # Port on Pod
  type: ClusterIP