
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
     env  : {{ .Values.service.metadata.labels.env }}
spec:
  selector:
    project: {{ .Values.app.project }}     # Selecting PODs with those Labels
  ports:
    - name      : {{ .Values.service.ports.name }}
      protocol  : {{ .Values.service.ports.protocol }}
      port      : {{ .Values.service.ports.port }}  # Port on Load Balancer
      targetPort: {{ .Values.service.ports.targetPort }}  # Port on Pod
  type: {{ .Values.service.type }}