---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.db.name }}
spec:
  selector:
    app: {{ .Values.db.name }}
  ports:
    - name: postgres
      port: {{ .Values.db.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app.name }}
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - name: sonar
      port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}