---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  rules:
  - host: sonar.prtest.tech
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.app.name }}
          servicePort: {{ .Values.app.containerPort }}
  tls:
  - hosts:
    - sonar.prtest.tech
    secretName: sonarqube-tls   