---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.secretname }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.db.name }}
type: Opaque
data:
  POSTGRESQL_USERNAME: c29uYXJfdXNlcg==
  POSTGRESQL_DATABASE: c29uYXJfZGI=
  POSTGRESQL_PASSWORD: UzBONFJRVUIz
  SONARQUBE_JDBC_URL: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXM6NTQzMi9zb25hcl9kYg==