build-backup:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - >-
      /kaniko/executor
      --context "backup"
      --dockerfile "backup/Dockerfile"
      --destination "gcr.io/internship87task8/backup:14.4.0-debian-11-r12"