apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup
spec:
  schedule: "14 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - env:
            - name: HOME
              value: /home/postgres
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: postgre-secret
            image: gcr.io/internship87task8/backup:14.4.0-debian-11-r12
            imagePullPolicy: Always
            name: backup 
            command:
            - bash
            - -c
            - "set -e; cd /home/postgres; pg_dump -h postgres-postgresql -Fc -U wagtail wagtail > backup_$(date '+%Y-%m-%d_%H-%M-%S').dump;  gsutil cp backup_$(date '+%Y-%m-%d_%H-%M-%S').dump gs://backuppostgre; gsutil ls gs://backuppostgre | sort -r | awk '{if(NR>7){print $0}}' | xargs -n1 -r gsutil rm"
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
            securityContext:
              runAsUser: 1001
          securityContext:
            fsGroup: 1001
          serviceAccount: backup
          serviceAccountName: backup
          imagePullSecrets:
          - name: gcr-json-key
          restartPolicy: OnFailure