---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.app.volume.name }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.app.volume.size }}