workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - test-stage

health-wagtail-dev:
  stage: test-stage
  image: wbitt/network-multitool
  script:
    - nslookup dev.prtest.tech

