build-app:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - >-
      /kaniko/executor
      --context "wagtail"
      --dockerfile "application/mysite/Dockerfile"
      --destination "gcr.io/internship87task8/myapp:latest"
