variables:
  KUBERNETES_SERVICE_ACCOUNT: gitlab-runner

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - >-
      sleep 10000
      /kaniko/executor
      --context "myapp"
      --dockerfile "myapp/Dockerfile"
      --destination "gcr.io/internship87task8/myapp:latest"